### ISSUE TITLE
Not working with font-awesome

### ISSUE THREAD

**Issue by ff-rboutotte** [bolandrm/sassc-rails#2]
In my attempt to get this working it is failing when it attempts to compile font-awesome assets. It looks like the font_path method is not supported. It is worth noting that this is coming from a css,erb filetype. Command I am running:
```
time RAILS_ENV=production bundle exec rake assets:precompile --trace
```
Exception backtrace:
```
rake aborted!
NoMethodError: undefined method `font_path' for #<Object:0x007fe5671367b8>
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/font-awesome-rails-4.3.0.0/app/assets/stylesheets/font-awesome.css.erb:15:in `block in singleton class'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/font-awesome-rails-4.3.0.0/app/assets/stylesheets/font-awesome.css.erb:-5:in `instance_eval'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/font-awesome-rails-4.3.0.0/app/assets/stylesheets/font-awesome.css.erb:-5:in `singleton class'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/font-awesome-rails-4.3.0.0/app/assets/stylesheets/font-awesome.css.erb:-7:in `__tilt_70311571807200'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-rails-0.0.1/lib/sassc/rails/importer.rb:37:in `import_for'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-rails-0.0.1/lib/sassc/rails/importer.rb:102:in `block (3 levels) in imports'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-rails-0.0.1/lib/sassc/rails/importer.rb:98:in `each'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-rails-0.0.1/lib/sassc/rails/importer.rb:98:in `block (2 levels) in imports'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-rails-0.0.1/lib/sassc/rails/importer.rb:95:in `each'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-rails-0.0.1/lib/sassc/rails/importer.rb:95:in `block in imports'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-rails-0.0.1/lib/sassc/rails/importer.rb:94:in `each'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-rails-0.0.1/lib/sassc/rails/importer.rb:94:in `imports'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-0.0.10/lib/sassc/importer.rb:12:in `block in setup'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-0.0.10/lib/sassc/engine.rb:22:in `call'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-0.0.10/lib/sassc/engine.rb:22:in `compile_data_context'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-0.0.10/lib/sassc/engine.rb:22:in `block in render'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-0.0.10/lib/sassc/script.rb:53:in `setup_custom_functions'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-0.0.10/lib/sassc/engine.rb:21:in `render'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-rails-0.0.1/lib/sassc/rails/template.rb:25:in `block in call'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/utils.rb:93:in `module_include'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sassc-rails-0.0.1/lib/sassc/rails/template.rb:24:in `call'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/sass_template.rb:21:in `call'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/loader.rb:123:in `block in load_asset_by_uri'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/loader.rb:121:in `each'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/loader.rb:121:in `load_asset_by_uri'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/cached_environment.rb:89:in `load_asset_by_uri'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/loader.rb:27:in `load'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/cached_environment.rb:22:in `block in initialize'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/cached_environment.rb:52:in `yield'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/cached_environment.rb:52:in `load'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/bundle.rb:22:in `block in call'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/bundle.rb:25:in `yield'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/bundle.rb:25:in `block in call'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/utils.rb:122:in `dfs'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/bundle.rb:26:in `call'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/loader.rb:123:in `block in load_asset_by_uri'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/loader.rb:121:in `each'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/loader.rb:121:in `load_asset_by_uri'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/cached_environment.rb:89:in `load_asset_by_uri'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/loader.rb:27:in `load'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/cached_environment.rb:22:in `block in initialize'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/cached_environment.rb:52:in `yield'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/cached_environment.rb:52:in `load'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/base.rb:65:in `find_asset'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/base.rb:72:in `find_all_linked_assets'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/manifest.rb:167:in `block in find'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/legacy.rb:47:in `block (2 levels) in logical_paths'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/path_utils.rb:188:in `block in stat_tree'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/path_utils.rb:172:in `block in stat_directory'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/path_utils.rb:169:in `each'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/path_utils.rb:169:in `stat_directory'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/path_utils.rb:187:in `stat_tree'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/legacy.rb:38:in `each'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/legacy.rb:38:in `block in logical_paths'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/legacy.rb:37:in `each'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/legacy.rb:37:in `logical_paths'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/manifest.rb:165:in `find'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/sprockets/manifest.rb:193:in `compile'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-3.0.0.beta.6/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/rboutotte/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/rboutotte/.rbenv/versions/2.1.1/bin/rake:23:in `load'
/Users/rboutotte/.rbenv/versions/2.1.1/bin/rake:23:in `<main>'
```

**Comment by bolandrm** [comment]
I ran into this issue as well - working on a fix:  https://github.com/bolandrm/sassc-rails/pull/4

**Comment by ff-rboutotte** [comment]
I have been able to get around this problem by moving to font-awesome-sass gem instead of font-awesome-rails for the time being. Not sure which one makes more sense to use in the long run.

**Comment by ff-rboutotte** [comment]
Looks like font-awesome-sass doesn't work either, I thought it was working, but I still had sass-rails referenced, now that I removed that I get this error below. Not something we can fix, but if sassc-rails is to be a direct replacement for sass-rails there should be some way to get around this.
```
LoadError: cannot load such file -- sass-rails
/Users/rboutotte/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
/Users/rboutotte/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
/Users/rboutotte/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
/Users/rboutotte/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
/Users/rboutotte/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/font-awesome-sass-4.3.2.1/lib/font-awesome-sass.rb:71:in `register_rails_engine'
```

**Comment by bolandrm** [comment]
I believe I fixed the font awesome issues with  https://github.com/bolandrm/sassc-rails/pull/4
