### ISSUE TITLE
Compressor crashing when building assets on Heroku

### ISSUE THREAD

**Issue by chrisnicola** [bolandrm/sassc-rails#37]
I can also reproduce this error if compression is enabled locally.

```
remote:        rake aborted!
remote:        SassC::SyntaxError: Error: error reading values after ,
remote:        on line 14370 of stdin
remote:        >> px, #ECECEC 4px, #E1E1E1 5px, #FFFFFF 6px, , , , , );
remote:        ------------------------------------------^
remote:        /tmp/build_bfac79ff2aeaeb533c89623080124288/vendor/bundle/ruby/2.2.0/gems/sassc-1.5.1/lib/sassc/engine.rb:38:in `render'
remote:        /tmp/build_bfac79ff2aeaeb533c89623080124288/vendor/bundle/ruby/2.2.0/bundler/gems/sassc-rails-3f36dd2b5159/lib/sassc/rails/compressor.rb:16:in `call'
remote:        /tmp/build_bfac79ff2aeaeb533c89623080124288/vendor/bundle/ruby/2.2.0/gems/sprockets-3.2.0/lib/sprockets/sass_compressor.rb:28:in `call'
remote:        /tmp/build_bfac79ff2aeaeb533c89623080124288/vendor/bundle/ruby/2.2.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
remote:        /tmp/build_bfac79ff2aeaeb533c89623080124288/vendor/bundle/ruby/2.2.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
```

**Comment by bolandrm** [comment]
Hey, is it possible to isolate a snippet of CSS that is eventually producing this error?

**Comment by chrisnicola** [comment]
Ok this was being caused by improper use of a linear gradient mixin. Actually this found a bug and some dead CSS for us.

**Comment by bolandrm** [comment]
great, thanks for the follow up!
